name: ataqv
channels:
        - conda-forge
        - bioconda
        - r
        - defaults
        - biobuilds
dependencies:
        - bedtools=2.27.1
        - bwa=0.7.15
        - macs2=2.1.1.20160309
        - picard # =2.8.1
        - fastqc=0.11.5
        - samtools=1.7
        - python=2.7
        - pysam # =0.11.2.1
        - pybedtools=0.8.0
        - r=3.5.1
        - r-ggplot2=3.1.0
        - r-ggrepel=0.8.0
        - r-dplyr # =0.7.7
        - r-tidyr=0.8.2
        - r-viridis
        - r-rcolorbrewer
        - bioconductor-genomicranges=1.34.0
        - r-optparse=1.6.0
        - r-glue=1.3.0
        - r-MASS=7.3-50
        - r-knitr
        - r-biocmanager
        - bioconductor-ggbio
        - sra-tools=2.8.1
        - fastx-toolkit=0.0.14
          # - cta=0.1.2
          # - r-cowplot=0.9.3
          # - python=3.5.3
          # - ataqv=1.0.0
